# Generated by Django 5.1.4 on 2025-02-09 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_aquisicao', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_rfid', models.CharField(max_length=50, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='bens/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonioweb.categoria')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonioweb.departamento')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonioweb.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.CharField(max_length=100)),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonioweb.bens')),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='patrimonioweb.departamento')),
                ('departamento_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='patrimonioweb.departamento')),
            ],
        ),
    ]
