# Generated by Django 5.1.4 on 2025-02-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonioweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameModel(
            old_name='Departamento',
            new_name='Departamentos',
        ),
        migrations.RenameModel(
            old_name='Fornecedor',
            new_name='Fornecedores',
        ),
        migrations.RenameModel(
            old_name='Movimentacao',
            new_name='Movimentacoes',
        ),
    ]
